# Deeper Configuration File
# This file contains default configuration values for the Deeper OSINT tool

# HTTP Configuration
http:
  timeout: 30s
  max_retries: 3
  retry_delay: 1s
  user_agent: "Deeper/1.0"

# Concurrency Configuration
concurrency:
  max_workers: 10
  rate_limit_per_second: 5

# Logging Configuration
logging:
  level: info
  format: json
  output: stderr

# Plugin Configuration
plugins:
  health_check_interval: 5m
  health_check_timeout: 30s
  enable_metrics: true

# Output Configuration
output:
  default_format: table
  enable_colors: true
  show_progress: true

# Security Configuration
security:
  enable_rate_limiting: true
  max_requests_per_minute: 300
  enable_input_validation: true

# Development Configuration
development:
  enable_debug_mode: false
  enable_profiling: false
  enable_trace_logging: false
